services:
  Atournayre\ToolboxBundle\Service\Date\DateService: '@atournayre_toolbox.date'

  Atournayre\ToolboxBundle\Service\Excel\Excel: '@atournayre_toolbox.excel'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleDateService: '@atournayre_toolbox.google.date'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarService:
    class: Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarService
    arguments:
      - '@Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleClientService'
      - '%atournayre_toolbox.google.calendar.allowed_role%'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarEventService: '@atournayre_toolbox.google.calendar.event'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleClientService:
    class: Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleClientService
    arguments:
      - '%atournayre_toolbox.google.client.application_name%'
      - '%atournayre_toolbox.google.client.configuration_directory%'
      - '%kernel.project_dir%'
      - '@filesystem'

  atournayre_toolbox.email.swiftmailer.service:
    class: Atournayre\ToolboxBundle\Service\Email\SwiftMailerService
    arguments:
      - '@swiftmailer.mailer.default'
      - '%atournayre_toolbox.email.noreply%'

  Atournayre\ToolboxBundle\Service\Email\EmailInterface: '@atournayre_toolbox.email.swiftmailer.service'
