services:
  Atournayre\ToolboxBundle\Service\Date\DateService: '@atournayre_toolbox.date'

  Atournayre\ToolboxBundle\Service\Excel\Excel: '@atournayre_toolbox.excel'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleDateService: '@atournayre_toolbox.google.date'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarService:
    class: Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarService
    arguments:
      - '@Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleClientService'
      - '%atournayre_toolbox.google.calendar.allowed_role%'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarEventService: '@atournayre_toolbox.google.calendar.event'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleClientService:
    class: Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleClientService
    arguments:
      - '%atournayre_toolbox.google.client.application_name%'
      - '%atournayre_toolbox.google.client.configuration_directory%'
      - '%kernel.project_dir%'
      - '@filesystem'

  atournayre_toolbox.email.swiftmailer.service:
    class: Atournayre\ToolboxBundle\Service\Email\SwiftMailerService
    arguments:
      - '@swiftmailer.mailer.default'
      - '%atournayre_toolbox.email.noreply%'

  Atournayre\ToolboxBundle\Service\Email\EmailInterface: '@atournayre_toolbox.email.swiftmailer.service'

  atournayre_toolbox.pdf.html2pdf.service:
    class: Atournayre\ToolboxBundle\Service\Pdf\Html2PdfGenerator
    arguments:
      - '%atournayre_toolbox.pdf.orientation%'
      - '%atournayre_toolbox.pdf.format%'
      - '%atournayre_toolbox.pdf.language%'
      - '%atournayre_toolbox.pdf.unicode%'
      - '%atournayre_toolbox.pdf.encoding%'
      - '%atournayre_toolbox.pdf.margins%'

  Atournayre\ToolboxBundle\Service\Pdf\PdfGeneratorInterface: '@atournayre_toolbox.pdf.html2pdf.service'

  Atournayre\ToolboxBundle\Service\Numbering\Numbering:
    class: Atournayre\ToolboxBundle\Service\Numbering\Numbering
    arguments:
      - '%atournayre_toolbox.numbering.pad_length%'
      - '%atournayre_toolbox.numbering.pad_string%'
      - '%atournayre_toolbox.numbering.pad_type%'
      - '%atournayre_toolbox.numbering.prefix%'
      - '%atournayre_toolbox.numbering.suffix%'
