services:
  Atournayre\ToolboxBundle\Service\Date\DateService: '@atournayre_toolbox.date'

  Atournayre\ToolboxBundle\Service\Excel\Excel: '@atournayre_toolbox.excel'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleDateService: '@atournayre_toolbox.google.date'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarService:
    class: Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarService
    arguments:
      - '@Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleClientService'
      - '%atournayre_toolbox.google.calendar.allowed_role%'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarEventService: '@atournayre_toolbox.google.calendar.event'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleClientService:
    class: Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleClientService
    arguments:
      - '%atournayre_toolbox.google.client.application_name%'
      - '%atournayre_toolbox.google.client.configuration_directory%'
      - '%kernel.project_dir%'
      - '@filesystem'

  atournayre_toolbox.email.swiftmailer.service:
    class: Atournayre\ToolboxBundle\Service\Email\SwiftMailerService
    arguments:
      - '@swiftmailer.mailer.default'
      - '%atournayre_toolbox.email.noreply%'

  Atournayre\ToolboxBundle\Service\Email\EmailInterface: '@atournayre_toolbox.email.swiftmailer.service'

  atournayre_toolbox.pdf.html2pdf.service:
    class: Atournayre\ToolboxBundle\Service\Pdf\Generator\Html2PdfGenerator
    arguments:
      - '%atournayre_toolbox.pdf.orientation%'
      - '%atournayre_toolbox.pdf.format%'
      - '%atournayre_toolbox.pdf.language%'
      - '%atournayre_toolbox.pdf.unicode%'
      - '%atournayre_toolbox.pdf.encoding%'
      - '%atournayre_toolbox.pdf.margins%'

  Atournayre\ToolboxBundle\Service\Pdf\Generator\PdfGeneratorInterface: '@atournayre_toolbox.pdf.html2pdf.service'

  Atournayre\ToolboxBundle\Service\Pdf\Merger\PdfMerger:
    class: Atournayre\ToolboxBundle\Service\Pdf\Merger\PdfMerger

  Atournayre\ToolboxBundle\Service\Numbering\Numbering:
    class: Atournayre\ToolboxBundle\Service\Numbering\Numbering
    arguments:
      - '%atournayre_toolbox.numbering.pad_length%'
      - '%atournayre_toolbox.numbering.pad_string%'
      - '%atournayre_toolbox.numbering.pad_type%'
      - '%atournayre_toolbox.numbering.prefix%'
      - '%atournayre_toolbox.numbering.suffix%'

  Atournayre\ToolboxBundle\EventListener\MaintenanceListener:
    class: Atournayre\ToolboxBundle\EventListener\MaintenanceListener
    arguments:
      - '@twig'
      - '@doctrine.orm.default_entity_manager'
      - '%atournayre_toolbox.maintenance%'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: 'onKernelRequest' }

  Atournayre\ToolboxBundle\Repository\ParameterRepository:
    class: Atournayre\ToolboxBundle\Repository\ParameterRepository
    arguments:
      - '@doctrine'
    tags:
      - { name: doctrine.repository_service }

  Atournayre\ToolboxBundle\Service\Maintenance\MaintenanceService:
    class: Atournayre\ToolboxBundle\Service\Maintenance\MaintenanceService

  Atournayre\ToolboxBundle\Command\MaintenanceCommand:
    class: Atournayre\ToolboxBundle\Command\MaintenanceCommand
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@Atournayre\ToolboxBundle\Service\Maintenance\MaintenanceService'
    tags:
      - { name: console.command, command: maintenance }

  Atournayre\ToolboxBundle\Command\EnvironmentCommand:
    class: Atournayre\ToolboxBundle\Command\EnvironmentCommand
    arguments:
      - '%atournayre_toolbox.environment_commands%'
    tags:
      - { name: console.command, command: init }

  Atournayre\ToolboxBundle\Form\ConfirmationType:
    class: Atournayre\ToolboxBundle\Form\ConfirmationType
    arguments:
      - '%atournayre_toolbox.crud_controller.delete.form_button_label%'
    tags:
      - { name: form.type }

  Atournayre\ToolboxBundle\Service\Insee\InseeToken:
    class: Atournayre\ToolboxBundle\Service\Insee\InseeToken
    arguments:
      - '%env(INSEE_CONSUMER_KEY)%'
      - '%env(INSEE_CONSUMER_SECRET)%'

  Atournayre\ToolboxBundle\Service\Insee\InseeSirene:
    class: Atournayre\ToolboxBundle\Service\Insee\InseeSirene

  Atournayre\ToolboxBundle\Service\Insee\InseeValidator:
    class: Atournayre\ToolboxBundle\Service\Insee\InseeValidator
    arguments:
      - '@Atournayre\ToolboxBundle\Service\Insee\InseeToken'
      - '@Atournayre\ToolboxBundle\Service\Insee\InseeSirene'

  Atournayre\ToolboxBundle\Service\Insee\InseeSirenValidator:
    class: Atournayre\ToolboxBundle\Service\Insee\InseeSirenValidator
    parent: Atournayre\ToolboxBundle\Service\Insee\InseeValidator
    autowire: false
    autoconfigure: false

  Atournayre\ToolboxBundle\Service\Insee\InseeSiretValidator:
    class: Atournayre\ToolboxBundle\Service\Insee\InseeSiretValidator
    parent: Atournayre\ToolboxBundle\Service\Insee\InseeValidator
    autowire: false
    autoconfigure: false
