services:
  Atournayre\ToolboxBundle\Service\Date\DateService: '@atournayre_toolbox.date'

  Atournayre\ToolboxBundle\Service\Excel\Excel: '@atournayre_toolbox.excel'

  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleDateService: '@atournayre_toolbox.google.date'
  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarService: '@atournayre_toolbox.google.calendar'
  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleCalendarEventService: '@atournayre_toolbox.google.calendar.event'
  Atournayre\ToolboxBundle\Service\Google\Calendar\GoogleClientService: '@atournayre_toolbox.google.client'

  Atournayre\ToolboxBundle\Service\Email\EmailInterface: '@atournayre_toolbox.email'
  atournayre_toolbox.email:
    class: Atournayre\ToolboxBundle\Service\Email\SwiftMailerService
